const buses = [
  {
    line: 7,
    direction: "Northbound",
    video: "https://youtu.be/-vRrQ_gT_yk?t=32",
  },
  {
    line: 7,
    direction: "Southbound",
    video: "https://youtu.be/KmCeOvBMEbs?t=21",
  },
  {
    line: 8,
    direction: "Northbound",
    video: "https://youtu.be/qqqCx1ITSz8?t=75",
  },
  {
    line: 8,
    direction: "Southbound",
    video: "https://youtu.be/32k-GPWVR9w?t=1",
  },
  {
    line: 9,
    direction: "Northbound",
    video: "https://youtu.be/MeP170iavig?t=78",
  },
  { line: 9, direction: "Southbound", video: "https://youtu.be/7IMUYTrC3YU" },
  {
    line: 10,
    direction: "Eastbound",
    video: "https://youtu.be/l74av8ThELU?t=32",
  },
  {
    line: 10,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 11,
    direction: "Northbound",
    video: "https://youtu.be/4LE4fia4914?t=36",
  },
  {
    line: 11,
    direction: "Southbound",
    video: "https://youtu.be/Q3hSw87VH1E?t=31",
  },
  {
    line: 12,
    direction: "Eastbound",
    video: "https://youtu.be/SIQ7uU44xtc?t=15",
  },
  {
    line: 12,
    direction: "Westbound",
    video: "https://youtu.be/JyepkjcU7fg?t=22",
  },
  {
    line: 13,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 13,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 14,
    direction: "Eastbound",
    video: "https://youtu.be/2fPmFemKvUQ?t=22",
  },
  {
    line: 14,
    direction: "Westbound",
    video: "https://youtu.be/80eOvnRRv-8?t=26",
  },
  {
    line: 15,
    direction: "Eastbound",
    video: "https://youtu.be/-0mT4jhn5v8?t=36",
  },
  {
    line: 15,
    direction: "Westbound",
    video: "https://youtu.be/bSQYWhwZ-jE?t=17",
  },
  {
    line: 16,
    direction: "Northbound",
    video: "https://youtu.be/QcnEdgjcAfw?t=33",
  },
  {
    line: 16,
    direction: "Southbound",
    video: "https://youtu.be/XNoqknnhNGI?t=15",
  },
  {
    line: 17,
    direction: "Northbound",
    video: "https://youtu.be/VtXh-EwvrJA?t=32",
  },
  {
    line: 17,
    direction: "Southbound",
    video: "https://youtu.be/5IGJn0meOAk?t=33",
  },
  {
    line: 19,
    direction: "Northbound",
    video: "https://youtu.be/8U4D8o1Xufw",
  },
  {
    line: 19,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 20,
    direction: "Eastbound",
    video: "https://youtu.be/HQjclNNNShs?t=23",
  },
  {
    line: 20,
    direction: "Westbound",
    video: "https://youtu.be/CP3CLjDQiDY?t=30",
  },
  {
    line: 21,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 21,
    direction: "Southbound",
    video: "https://youtu.be/0jRkdXgeqqw?t=76",
  },
  { line: 22, direction: "Northbound", video: "https://youtu.be/BnhVG3HlDK4" },
  {
    line: 22,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 23,
    direction: "Northbound",
    video: "https://youtu.be/I2UVKVWdb1M?t=31",
  },
  {
    line: 23,
    direction: "Southbound",
    video: "https://youtu.be/JwCbnhYN_fU?t=77",
  },
  {
    line: 24,
    direction: "Northbound",
    video: "https://youtu.be/lyzL-dP2jqg?t=22",
  },
  { line: 24, direction: "Southbound", video: "https://youtu.be/wTU4bFeohYo" },
  {
    line: 25,
    direction: "Northbound",
    video: "https://youtu.be/Rqd5J0ae0XQ?t=33",
  },
  { line: 25, direction: "Southbound", video: "https://youtu.be/wK7I3Oa-Boo" },
  {
    line: 26,
    direction: "Eastbound",
    video: "https://youtu.be/O81Ju6ZqMI4?t=12",
  },
  {
    line: 26,
    direction: "Westbound",
    video: "https://youtu.be/GLBPIV2tVEo?t=21",
  },
  {
    line: 28,
    direction: "Eastbound",
    video: "https://youtu.be/aJc6hD0aiQE",
  },
  {
    line: 28,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 29,
    direction: "Northbound",
    video: "https://youtu.be/XPqv2JxYqs4?t=75",
  },
  { line: 29, direction: "Southbound", video: "https://youtu.be/RxOW5eKDf5s" },
  {
    line: 30,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 30,
    direction: "Southbound",
    video: "https://youtu.be/Sdh-iIxxesQ?t=34",
  },
  {
    line: 31,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 31,
    direction: "Southbound",
    video: "https://youtu.be/OjFeQurFkb4?t=76",
  },
  {
    line: 32,
    direction: "Eastbound",
    video: "https://youtu.be/V6-AudgF8jw?t=20",
  },
  {
    line: 32,
    direction: "Westbound",
    video: "https://youtu.be/uLCzAFB_cSU?t=31",
  },
  { line: 33, direction: "Northbound", video: "https://youtu.be/26OdzJZuY9U" },
  {
    line: 33,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 34,
    direction: "Eastbound",
    video: "https://youtu.be/OSbar0qXYc8?t=30",
  },
  {
    line: 34,
    direction: "Westbound",
    video: "https://youtu.be/nBW0nGIx34Y?t=17",
  },
  { line: 35, direction: "Northbound", video: "https://youtu.be/CI7TXSKQXqg" },
  {
    line: 35,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 36,
    direction: "Eastbound",
    video: "https://youtu.be/isbPvsZ_Yu4?t=32",
  },
  { line: 36, direction: "Westbound", video: "https://youtu.be/oHIWbPytEiw" },
  { line: 37, direction: "Northbound", video: "https://youtu.be/PuisPDX50OU" },
  { line: 37, direction: "Southbound", video: "https://youtu.be/OmCTyEijfYk" },
  {
    line: 38,
    direction: "Eastbound",
    video: "https://youtu.be/bd8c4w19JNE?t=4",
  },
  {
    line: 38,
    direction: "Westbound",
    video: "https://youtu.be/Dbd8rCVnKSY?t=38",
  },
  {
    line: 39,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 39,
    direction: "Westbound",
    video: "https://youtu.be/LtcPs5jyxdQ?t=11",
  },
  {
    line: 40,
    direction: "Eastbound",
    video: "https://youtu.be/goDzg4TRjqc?t=49",
  },
  {
    line: 40,
    direction: "Westbound",
    video: "https://youtu.be/pRkmIAEXtmY?t=33",
  },
  {
    line: 41,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 41, direction: "Southbound", video: "https://youtu.be/6R2aCNRPsmE" },
  {
    line: 42,
    direction: "Eastbound",
    video: "https://youtu.be/3ykWAGULdXE?t=32",
  },
  {
    line: 42,
    direction: "Westbound",
    video: "https://youtu.be/eTNRJ_hm3Ow?t=31",
  },
  {
    line: 43,
    direction: "Northbound",
    video: "https://youtu.be/QVqQS8L8EpY?t=33",
  },
  {
    line: 43,
    direction: "Southbound",
    video: "https://youtu.be/cnmsHzwL1hA?t=16",
  },
  {
    line: 44,
    direction: "Northbound",
    video: "https://youtu.be/aL5rjOCLtoI?t=8",
  },
  {
    line: 44,
    direction: "Southbound",
    video: "https://youtu.be/ZJN8mNp6xIM?t=31",
  },
  {
    line: 45,
    direction: "Northbound",
    video: "https://youtu.be/zHc_2ZfmWf4?t=30",
  },
  {
    line: 45,
    direction: "Southbound",
    video: "https://youtu.be/ir9W2h56-6I?t=36",
  },
  { line: 46, direction: "Northbound", video: "https://youtu.be/_JgivoCAa84" },
  {
    line: 46,
    direction: "Southbound",
    video: "https://youtu.be/-KHdWjYqNXo?t=30",
  },
  {
    line: 47,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 47,
    direction: "Southbound",
    video: "https://youtu.be/wGebWzMXP9Q?t=76",
  },
  {
    line: 48,
    direction: "Eastbound",
    video: "https://youtu.be/meDVQV-k5HA?t=20",
  },
  {
    line: 48,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 49,
    direction: "Eastbound",
    video: "https://youtu.be/VTQikN_j48U?t=32",
  },
  { line: 49, direction: "Westbound", video: "https://youtu.be/xqEvA5armbU" },
  {
    line: 50,
    direction: "Eastbound",
    video: "https://youtu.be/YPMqAObhlZg?t=29",
  },
  {
    line: 50,
    direction: "Westbound",
    video: "https://youtu.be/TpJInt842bM?t=2",
  },
  {
    line: 51,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 51,
    direction: "Southbound",
    video: "https://youtu.be/W-21TQFIk3g?t=20",
  },
  {
    line: 52,
    direction: "Eastbound",
    video: "https://youtu.be/vUWVuwvKrc0?t=18",
  },
  {
    line: 52,
    direction: "Westbound",
    video: "https://youtu.be/bqmYygEQtP4?t=32",
  },
  {
    line: 53,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 53, direction: "Westbound", video: "https://youtu.be/BzIe2A7L_pc" },
  {
    line: 54,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 54, direction: "Westbound", video: "https://youtu.be/1PHOl6U0pMs" },
  { line: 55, direction: "Northbound", video: "https://youtu.be/O0oG4X1IHA4" },
  {
    line: 55,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 56,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 56,
    direction: "Southbound",
    video: "https://youtu.be/eCEhTJFfJwg?t=17",
  },
  {
    line: 57,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 57, direction: "Southbound", video: "https://youtu.be/EcrtIghWJUw" },
  {
    line: 59,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 59, direction: "Westbound", video: "https://youtu.be/MHslbnbLAik" },
  {
    line: 60,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 60, direction: "Westbound", video: "https://youtu.be/owfKEKVUEiE" },
  {
    line: 61,
    direction: "Northbound",
    video: "https://youtu.be/gAZflIKPOxI?t=77",
  },
  { line: 61, direction: "Southbound", video: "https://youtu.be/lc887esjIGQ" },
  {
    line: 62,
    direction: "Eastbound",
    video: "https://youtu.be/9VCOSHWYTPM?t=25",
  },
  {
    line: 62,
    direction: "Westbound",
    video: "https://youtu.be/menUids1YZI?t=76",
  },
  { line: 63, direction: "Northbound", video: "https://youtu.be/v5qzSn8nKBs" },
  {
    line: 63,
    direction: "Southbound",
    video: "https://youtu.be/WuDcesUGOEY?t=80",
  },
  {
    line: 64,
    direction: "Northbound",
    video: "https://youtu.be/CS9SU_pWUAs?t=76",
  },
  { line: 64, direction: "Southbound", video: "https://youtu.be/ciWh9cXnT3M" },
  {
    line: 65,
    direction: "Northbound",
    video: "https://youtu.be/ABNTCLEOPnE?t=29",
  },
  { line: 65, direction: "Southbound", video: "https://youtu.be/p_F7Jep_xAQ" },
  {
    line: 66,
    direction: "Northbound",
    video: "https://youtu.be/5viNk3mvde4?t=76",
  },
  {
    line: 66,
    direction: "Southbound",
    video: "https://youtu.be/1F4coqRwFmk?t=60",
  },
  {
    line: 67,
    direction: "Northbound",
    video: "https://youtu.be/Xsnw39ccLzM?t=27",
  },
  {
    line: 67,
    direction: "Southbound",
    video: "https://youtu.be/eApsFFkzI9s?t=30",
  },
  {
    line: 68,
    direction: "Northbound",
    video: "https://youtu.be/8ouMNEC4nzU?t=33",
  },
  { line: 68, direction: "Southbound", video: "https://youtu.be/x6mWX2L9em0" },
  { line: 69, direction: "Northbound", video: "https://youtu.be/kdIC7x5cFk0" },
  { line: 69, direction: "Southbound", video: "https://youtu.be/B9fZxh0o72Y" },
  {
    line: 70,
    direction: "Eastbound",
    video: "https://youtu.be/yUOouMxiwtk?t=23",
  },
  { line: 70, direction: "Westbound", video: "https://youtu.be/0HIOXk0ffz4" },
  { line: 71, direction: "Northbound", video: "https://youtu.be/qeHGeDUe2j0" },
  {
    line: 71,
    direction: "Southbound",
    video: "https://youtu.be/ux6ndTBav5k?t=18",
  },
  {
    line: 72,
    direction: "Northbound",
    video: "https://youtu.be/Wqqx1nPZ1mc?t=70",
  },
  {
    line: 72,
    direction: "Southbound",
    video: "https://youtu.be/NEpMRkII1sk?t=77",
  },
  { line: 73, direction: "Northbound", video: "https://youtu.be/2jRsooP1AYE" },
  {
    line: 73,
    direction: "Southbound",
    video: "https://youtu.be/VqtHN2TdHRc?t=34",
  },
  {
    line: 74,
    direction: "Northbound",
    video: "https://youtu.be/4IIL88ZUv48?t=76",
  },
  {
    line: 74,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 75,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 75, direction: "Southbound", video: "https://youtu.be/V4NWn8W1Pa8" },
  {
    line: 76,
    direction: "Northbound",
    video: "https://youtu.be/avNP35jZvlQ?t=18",
  },
  {
    line: 76,
    direction: "Southbound",
    video: "https://youtu.be/sNu42dNmwpE?t=57",
  },
  {
    line: 77,
    direction: "Northbound",
    video: "https://youtu.be/w0coX2OVvYU?t=16",
  },
  {
    line: 77,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 78,
    direction: "Eastbound",
    video: "https://youtu.be/U_7WTpKlm5o?t=8",
  },
  {
    line: 78,
    direction: "Westbound",
    video: "https://youtu.be/WJ2mvuUwXLI?t=78",
  },
  { line: 79, direction: "Northbound", video: "https://youtu.be/RfVQViCL9IQ" },
  {
    line: 79,
    direction: "Southbound",
    video: "https://youtu.be/5nk03gzMctg?t=76",
  },
  {
    line: 80,
    direction: "Eastbound",
    video: "https://youtu.be/jRNx5P6ft3k?t=35",
  },
  { line: 80, direction: "Westbound", video: "https://youtu.be/pkOQFqbq1Ko" },
  {
    line: 81,
    direction: "Northbound",
    video: "https://youtu.be/QwLWoc70TU4?t=31",
  },
  {
    line: 81,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 82,
    direction: "Eastbound",
    video: "https://youtu.be/Iava9rOnJi8?t=23",
  },
  { line: 82, direction: "Westbound", video: "https://youtu.be/3SYG53CI3c8" },
  {
    line: 83,
    direction: "Northbound",
    video: "https://youtu.be/cBtyzvLG7Iw?t=25",
  },
  { line: 83, direction: "Southbound", video: "https://youtu.be/xeuNCMu_oto" },
  {
    line: 84,
    direction: "Eastbound",
    video: "https://youtu.be/uhXtb4_0Lm4?t=31",
  },
  {
    line: 84,
    direction: "Westbound",
    video: "https://youtu.be/frfnWxonu3w?t=9",
  },
  {
    line: 85,
    direction: "Eastbound",
    video: "https://youtu.be/aEJ44Src5nM?t=16",
  },
  {
    line: 85,
    direction: "Westbound",
    video: "https://youtu.be/ai-8PRe1Yyo?t=32",
  },
  {
    line: 86,
    direction: "Eastbound",
    video: "https://youtu.be/EBoo22z-6gM?t=4",
  },
  {
    line: 86,
    direction: "Westbound",
    video: "https://youtu.be/J1fxL0e1Ou4?t=75",
  },
  {
    line: 87,
    direction: "Eastbound",
    video: "https://youtu.be/ajjeo5HOX3c?t=49",
  },
  {
    line: 87,
    direction: "Westbound",
    video: "https://youtu.be/2jA1v0u2Ztw?t=75",
  },
  {
    line: 88,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 88, direction: "Westbound", video: "https://youtu.be/mthANiDZak0" },
  {
    line: 89,
    direction: "Northbound",
    video: "https://youtu.be/q_JXs2YoOEc?t=82",
  },
  {
    line: 89,
    direction: "Southbound",
    video: "https://youtu.be/LZKFHIZUxME?t=8",
  },
  {
    line: 90,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 90, direction: "Southbound", video: "https://youtu.be/RC4v1gCsTGI" },
  {
    line: 91,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 91, direction: "Southbound", video: "https://youtu.be/56oq8dVj9nY" },
  {
    line: 92,
    direction: "Northbound",
    video: "https://youtu.be/dydiBSR6Ld4?t=29",
  },
  { line: 92, direction: "Southbound", video: "https://youtu.be/5GGbvy4i2ms" },
  {
    line: 93,
    direction: "Northbound",
    video: "https://youtu.be/FzBOF53a0v4?t=7",
  },
  { line: 93, direction: "Southbound", video: "https://youtu.be/K8EaXbRf3n8" },
  {
    line: 94,
    direction: "Eastbound",
    video: "https://youtu.be/Gq4UaKukthI?t=32",
  },
  {
    line: 94,
    direction: "Westbound",
    video: "https://youtu.be/g8-PLeosjss?t=30",
  },
  {
    line: 95,
    direction: "Eastbound",
    video: "https://youtu.be/lxaPq8JZ7bg?t=29",
  },
  {
    line: 95,
    direction: "Westbound",
    video: "https://youtu.be/n5GXPN-trJo?t=30",
  },
  {
    line: 96,
    direction: "Eastbound",
    video: "https://youtu.be/UxWywXHSbq4?t=33",
  },
  {
    line: 96,
    direction: "Westbound",
    video: "https://youtu.be/kZP2hIiTR8I?t=1",
  },
  {
    line: 97,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 97,
    direction: "Southbound",
    video: "https://youtu.be/Q62GZHmD2I4?t=76",
  },
  {
    line: 98,
    direction: "Eastbound",
    video: "https://youtu.be/gKp5ZnloHSw?t=30",
  },
  {
    line: 98,
    direction: "Westbound",
    video: "https://youtu.be/sas7qbYm2O4?t=17",
  },
  {
    line: 99,
    direction: "Northbound",
    video: "https://youtu.be/aTpqPoAP_9c?t=32",
  },
  {
    line: 99,
    direction: "Southbound",
    video: "https://youtu.be/By4iEh93VOE?t=3",
  },
  {
    line: 100,
    direction: "Northbound",
    video: "https://youtu.be/tFRe6BqozSc?t=23",
  },
  {
    line: 100,
    direction: "Southbound",
    video: "https://youtu.be/vhDFCMXUgBI?t=1",
  },
  {
    line: 101,
    direction: "Eastbound",
    video: "https://youtu.be/sNsxqinIxiA?t=1",
  },
  {
    line: 101,
    direction: "Westbound",
    video: "https://youtu.be/bXo6VhrVG-M?t=5",
  },
  {
    line: 102,
    direction: "Northbound",
    video: "https://youtu.be/FdGDgHx87e0?t=44",
  },
  {
    line: 102,
    direction: "Southbound",
    video: "https://youtu.be/Y9uGAIMbKD0?t=15",
  },
  {
    line: 104,
    direction: "Northbound",
    video: "https://youtu.be/owUf3DMz5ws?t=30",
  },
  {
    line: 104,
    direction: "Southbound",
    video: "https://youtu.be/9im0hz5D7e0?t=32",
  },
  { line: 105, direction: "Northbound", video: "https://youtu.be/XUhSSaxBSf0" },
  {
    line: 105,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 106,
    direction: "Eastbound",
    video: "https://youtu.be/5pk2qvULs9I?t=16",
  },
  {
    line: 106,
    direction: "Westbound",
    video: "https://youtu.be/kAyuGC0RgsY?t=32",
  },
  {
    line: 107,
    direction: "Both Ways",
    video: "https://youtu.be/LSFvjL6zv8c?t=75",
  },
  {
    line: 108,
    direction: "Eastbound",
    video: "https://youtu.be/-BklhsI3r9o?t=32",
  },
  {
    line: 108,
    direction: "Westbound",
    video: "https://youtu.be/ssPw3mzhG6Q?t=16",
  },
  {
    line: 109,
    direction: "Northbound",
    video: "https://youtu.be/bdmF2esztME?t=26",
  },
  {
    line: 109,
    direction: "Southbound",
    video: "https://youtu.be/uwTwfiTiEjc?t=21",
  },
  {
    line: 110,
    direction: "Northbound",
    video: "https://youtu.be/eymMJAkNL5I?t=76",
  },
  {
    line: 110,
    direction: "Southbound",
    video: "https://youtu.be/iHYaMEJfUSY?t=76",
  },
  {
    line: 111,
    direction: "Northbound",
    video: "https://youtu.be/Bop_Q5h0fkE?t=30",
  },
  {
    line: 111,
    direction: "Southbound",
    video: "https://youtu.be/By_ruIbCNMw?t=29",
  },
  {
    line: 112,
    direction: "Northbound",
    video: "https://youtu.be/GX0tP39BD28?t=12",
  },
  {
    line: 112,
    direction: "Southbound",
    video: "https://youtu.be/msGsmrA7hr4?t=30",
  },
  {
    line: 113,
    direction: "Eastbound",
    video: "https://youtu.be/YD5hxQjTg-c?t=32",
  },
  {
    line: 113,
    direction: "Westbound",
    video: "https://youtu.be/UnL8kWgb6FI?t=17",
  },
  {
    line: 115,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 115, direction: "Westbound", video: "https://youtu.be/qEeSII4yY2o" },
  {
    line: 116,
    direction: "Eastbound",
    video: "https://youtu.be/Ceq4R_R0b8U?t=75",
  },
  { line: 116, direction: "Westbound", video: "https://youtu.be/61kDRzp0ocs" },
  {
    line: 117,
    direction: "Northbound",
    video: "https://youtu.be/3n5yp5EM1Wk?t=33",
  },
  {
    line: 117,
    direction: "Southbound",
    video: "https://youtu.be/_MSqL8WOBT4?t=23",
  },
  {
    line: 118,
    direction: "Eastbound",
    video: "https://youtu.be/RHfb4LiJ18E?t=34",
  },
  { line: 118, direction: "Westbound", video: "https://youtu.be/DkGY4oodq0Y" },
  {
    line: 119,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 119,
    direction: "Westbound",
    video: "https://youtu.be/CezvB9xEUkk?t=30",
  },
  {
    line: 120,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 120,
    direction: "Westbound",
    video: "https://youtu.be/ub5_TqphsB0?t=18",
  },
  {
    line: 121,
    direction: "Eastbound",
    video: "https://youtu.be/c1eevOJE7d0?t=4",
  },
  { line: 121, direction: "Westbound", video: "https://youtu.be/KQVeW8Ns7mg" },
  {
    line: 122,
    direction: "Eastbound",
    video: "https://youtu.be/_iSb0p9A3eE?t=15",
  },
  { line: 122, direction: "Westbound", video: "https://youtu.be/q1gqk9WMacA" },
  {
    line: 123,
    direction: "Northbound",
    video: "https://youtu.be/E7LPw6rG_ew?t=1",
  },
  {
    line: 123,
    direction: "Southbound",
    video: "https://youtu.be/oLKC34Gn0pE?t=76",
  },
  {
    line: 124,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 124, direction: "Westbound", video: "https://youtu.be/a0tZ5yedyNU" },
  { line: 125, direction: "Eastbound", video: "https://youtu.be/dB8plmzDfaY" },
  {
    line: 125,
    direction: "Westbound",
    video: "https://youtu.be/Ots0CEm6TkM?t=2",
  },
  {
    line: 126,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 126,
    direction: "Southbound",
    video: "https://youtu.be/ZZ1oEr542yo?t=1",
  },
  {
    line: 127,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 127,
    direction: "Westbound",
    video: "https://youtu.be/5qrdlw8rkCA?t=75",
  },
  {
    line: 129,
    direction: "Northbound",
    video: "https://youtu.be/hQ5MjCymdMI?t=30",
  },
  {
    line: 129,
    direction: "Southbound",
    video: "https://youtu.be/30uD5q1CwFM?t=23",
  },
  {
    line: 130,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 130, direction: "Southbound", video: "https://youtu.be/VgzRNXg6UHY" },
  {
    line: 131,
    direction: "Eastbound",
    video: "https://youtu.be/COLKVrk_Onw?t=75",
  },
  {
    line: 131,
    direction: "Westbound",
    video: "https://youtu.be/MRuJhnLsNTM?t=1",
  },
  {
    line: 132,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 132,
    direction: "Westbound",
    video: "https://youtu.be/EsVaRpSFODM?t=75",
  },
  {
    line: 133,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 133,
    direction: "Southbound",
    video: "https://youtu.be/NqQHbKJH9Ok?t=75",
  },
  {
    line: 134,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 134,
    direction: "Southbound",
    video: "https://youtu.be/ZSsCgGFMdJY?t=75",
  },
  {
    line: 135,
    direction: "Eastbound",
    video: "https://youtu.be/xNUUj2z6Iwc?t=25",
  },
  {
    line: 135,
    direction: "Westbound",
    video: "https://youtu.be/QbB8F-zkAQ8?t=20",
  },
  {
    line: 160,
    direction: "Northbound",
    video: "https://youtu.be/Hh3I5HuknFs?t=75",
  },
  {
    line: 160,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 161,
    direction: "Eastbound",
    video: "https://youtu.be/K9Zn06OZr3M?t=15",
  },
  {
    line: 161,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 162,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 162,
    direction: "Westbound",
    video: "https://youtu.be/JNtmVdpBaLw?t=30",
  },
  { line: 165, direction: "Eastbound", video: "https://youtu.be/opB3U-1BtQc" },
  {
    line: 165,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 167,
    direction: "Northbound",
    video: "https://youtu.be/TZA6xBN9p2o?t=32",
  },
  {
    line: 167,
    direction: "Southbound",
    video: "https://youtu.be/_M2In_GVYNQ?t=15",
  },
  {
    line: 168,
    direction: "Northbound",
    video: "https://youtu.be/VTI_iVwNcgk?t=30",
  },
  {
    line: 168,
    direction: "Southbound",
    video: "https://youtu.be/Odg83aWC8EU?t=29",
  },
  {
    line: 169,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  { line: 169, direction: "Westbound", video: "https://youtu.be/gxKYyO00PL0" },
  { line: 171, direction: "Both Ways", video: "https://youtu.be/vkUzdJFUP_o" },
  {
    line: 175,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 175,
    direction: "Southbound",
    video: "https://youtu.be/4Oc2-2RdgrA?t=76",
  },
  {
    line: 176,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 176,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 189,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 189,
    direction: "Westbound",
    video: "https://youtu.be/gJs7jQIZ_k4?t=32",
  },
  // {
  //   type: "dt",
  //   line: 141,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "dt",
  //   line: 141,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "dt",
  //   line: 142,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "dt",
  //   line: 142,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "dt",
  //   line: 143,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "dt",
  //   line: 143,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "dt",
  //   line: 144,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "dt",
  //   line: 144,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "dt",
  //   line: 145,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "dt",
  //   line: 145,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  {
    type: "express",
    line: 900,
    direction: "Northbound",
    video: "https://youtu.be/rlK4OrAWJwI?t=15",
  },
  {
    type: "express",
    line: 900,
    direction: "Southbound",
    video: "https://youtu.be/7mPmDXEk4eE?t=35",
  },
  // {
  //   type: "express",
  //   line: 902,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 902,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 903,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 903,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 905,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 905,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 913,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 913,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 924,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 924,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 925,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 925,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 927,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 927,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 929,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 929,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 935,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 935,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 937,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 937,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 939,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 939,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 941,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 941,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 944,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 944,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 945,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 945,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 952,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 952,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 953,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 953,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 954,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 954,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 960,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 960,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 984,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 984,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 985,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 985,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 986,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 986,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 989,
  //   direction: "Northbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 989,
  //   direction: "Southbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 995,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 995,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 996,
  //   direction: "Eastbound",
  //   video: "https://youtu.be/test?t=35",
  // },
  // {
  //   type: "express",
  //   line: 996,
  //   direction: "Westbound",
  //   video: "https://youtu.be/test?t=35",
  // },
];

const streetcars = [
  {
    line: 501,
    direction: "EB",
    video: "https://youtu.be/Deogvppc0K4?t=63",
  },
  {
    line: 501,
    direction: "WB",
    video: "https://youtu.be/nGFYo5A7EK8",
  },
  {
    line: 503,
    direction: "EB",
    video: "https://youtu.be/hGj7TQUAQjQ?t=33",
  },
  {
    line: 503,
    direction: "WB",
    video: "https://youtu.be/1puG7NPjlIk?t=17",
  },
  {
    line: 504,
    direction: "EB",
    video: "https://youtu.be/y4vc3msbtP0",
  },
  {
    line: 504,
    direction: "WB",
    video: "https://youtu.be/bELG0gB4h5E",
  },
  {
    line: 505,
    direction: "EB",
    video: "https://youtu.be/YyFLQ8LBiAw?t=33",
  },
  {
    line: 505,
    direction: "WB",
    video: "https://youtu.be/TGV8llDmjl8",
  },
  {
    line: 506,
    direction: "EB",
    video: "https://youtu.be/xY4k0kzujf8?t=120",
  },
  {
    line: 506,
    direction: "WB",
    video: "https://youtu.be/avKMbCLb3x4?t=33",
  },
  {
    line: 508,
    direction: "EB",
    video: "https://youtu.be/HF5B0haQs_c?t=101",
  },
  // {
  //   line: 508,
  //   direction: "WB",
  //   video: "https://youtu.be/test?t=00",
  // },
  {
    line: 509,
    direction: "EB",
    video: "https://youtu.be/Zj7sLBuWMUc?t=35",
  },
  {
    line: 509,
    direction: "WB",
    video: "https://youtu.be/w3jV6kDt6ls?t=09",
  },
  {
    line: 510,
    direction: "NB",
    video: "https://youtu.be/NhCpWymVKIo?t=96",
  },
  {
    line: 510,
    direction: "SB",
    video: "https://youtu.be/iNUdeL1_Q_Q?t=35",
  },
  {
    line: 511,
    direction: "NB",
    video: "https://youtu.be/mZy7uJA7mKk?t=40",
  },
  {
    line: 511,
    direction: "SB",
    video: "https://youtu.be/ltCkM932v6g?t=27",
  },
  {
    line: 512,
    direction: "EB",
    video: "https://youtu.be/RojzehF3_38?t=33",
  },
  {
    line: 512,
    direction: "WB",
    video: "https://youtu.be/enaD-33GBvU?t=13",
  },
];

const subway = [
  {
    line: 1,
    direction: "NB",
    video: "https://youtu.be/hiARDxmAWi8?t=12",
  },
  {
    line: 1,
    direction: "SB",
    video: "https://youtu.be/fksb0X8z9Cs?t=57",
  },
  {
    line: 2,
    direction: "EB",
    video: "https://youtu.be/8lQOHmEQ8FQ?t=34",
  },
  {
    line: 2,
    direction: "WB",
    video: "https://youtu.be/pu-WSiXf3ng?t=16",
  },
  {
    line: 3,
    direction: "EB",
    video: "https://youtu.be/cTUf4N6-P50?t=67",
  },
  {
    line: 3,
    direction: "WB",
    video: "https://youtu.be/kQjK8tHTqnE?t=32",
  },
  {
    line: 4,
    direction: "EB",
    video: "https://youtu.be/4zEF7aYgCv0?t=57",
  },
  {
    line: 4,
    direction: "WB",
    video: "https://youtu.be/qCQWeUktbp4?t=58",
  },
];

export { buses, streetcars, subway };
